services:
  web:
    build: .
    volumes:
      - .:/BIMS
    ports:
      - 8000:8000
    depends_on:
      - db
    image: bims_image
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - default

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=bims
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    container_name: postgres_db
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"  
      PGADMIN_DEFAULT_PASSWORD: "admin123" 
    ports:
      - "5050:80"  
    networks:
      - default

volumes:
  postgres_data:
