# Generated by Django 4.0.1 on 2024-09-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='unit'),
        ),
    ]
