# Generated by Django 4.0.1 on 2024-10-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='unit'),
        ),
    ]
