# Generated by Django 5.1.1 on 2024-09-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deletion_requested',
            field=models.BooleanField(default=False, verbose_name='deletion requested'),
        ),
    ]
