# Generated by Django 4.0.1 on 2024-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_deletion_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='midde name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='unit'),
        ),
    ]
