
# Generated by Django 5.1.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Ack_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_sample_id', models.IntegerField(blank=True, null=True)),
                ('officer_signature', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300, null=True)),
                ('sex', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('clinical_diagnosis', models.CharField(max_length=300, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=300)),
                ('date_collected', models.DateField(null=True)),
                ('consent_form', models.FileField(blank=True, null=True, upload_to='')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ack_Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('sample_id', models.IntegerField(blank=True, null=True)),
                ('sample_type', models.CharField(max_length=100, null=True)),
                ('quantity_volume', models.CharField(max_length=100, null=True)),
                ('container_location', models.CharField(max_length=100, null=True)),
                ('create_ack_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.create_ack_receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erb_approval', models.FileField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(max_length=300, null=True)),
                ('sex', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('clinical_diagnosis', models.CharField(max_length=300, null=True)),

                ('amount', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_start_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approve_Reject_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_reject', models.CharField(max_length=100, null=True)),
                ('attach_file', models.FileField(blank=True, null=True, upload_to='')),
                ('reject_reason', models.CharField(max_length=300, null=True)),
                ('no_available_samples', models.CharField(max_length=100, null=True)),
                ('create_ack_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.create_ack_receipt')),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='Research_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('title', models.CharField(max_length=300, null=True)),
                ('principal_investigator', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('anticipated_initiation_date', models.DateField(null=True)),
                ('anticipated_completion_date', models.DateField(null=True)),
                ('erb_number', models.CharField(max_length=300, null=True)),
                ('funding_source', models.CharField(max_length=300, null=True)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='RS_Comorbidities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity', models.CharField(blank=True, max_length=300)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='RS_Lab_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labtest', models.CharField(blank=True, max_length=300)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='RS_Step4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_samples', models.CharField(max_length=255, null=True)),
                ('time_points', models.IntegerField(blank=True, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('interval_unit', models.CharField(blank=True, max_length=100)),
                ('start_date_ddmmyyyy', models.DateField(null=True)),
                ('start_date_mmyyyy', models.CharField(blank=True, max_length=7, null=True)),
                ('start_date_yyyy', models.IntegerField(blank=True, null=True)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='RS_Step5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('different_sources', models.CharField(max_length=255, null=True)),
                ('num_participants', models.IntegerField(blank=True, null=True)),
                ('multiple_timepoints_each', models.CharField(max_length=255, null=True)),
                ('time_points', models.IntegerField(blank=True, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('interval_unit', models.CharField(blank=True, max_length=100)),
                ('start_date_ddmmyyyy', models.DateField(null=True)),
                ('start_date_mmyyyy', models.CharField(blank=True, max_length=7, null=True)),
                ('start_date_yyyy', models.IntegerField(blank=True, null=True)),
                ('collection_date_ddmmyyyy', models.DateField(null=True)),
                ('collection_date_mmyyyy', models.CharField(blank=True, max_length=7, null=True)),
                ('collection_date_yyyy', models.IntegerField(blank=True, null=True)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labtest', models.CharField(blank=True, max_length=300)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.samples')),
            ],
        ),
        migrations.CreateModel(
            name='Comorbidities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity', models.CharField(blank=True, max_length=300)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.samples')),
            ],
        ),
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.samples')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freezer_num', models.CharField(blank=True, max_length=300, null=True)),
                ('shelf_num', models.IntegerField(blank=True, null=True)),
                ('rack_num', models.IntegerField(blank=True, null=True)),
                ('box_num', models.IntegerField(blank=True, null=True)),
                ('container', models.CharField(blank=True, max_length=100)),
                ('aliquot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.aliquot')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.samples')),
            ],
        ),
    ]
