# Generated by Django 4.0.1 on 2024-09-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('clinical_diagnosis', models.CharField(max_length=150, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('date_collected', models.DateField(null=True)),
                ('consent_form', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freezer_num', models.IntegerField(blank=True, null=True)),
                ('shelf_num', models.IntegerField(blank=True, null=True)),
                ('rack_num', models.IntegerField(blank=True, null=True)),
                ('box_num', models.IntegerField(blank=True, null=True)),
                ('container', models.CharField(blank=True, max_length=20)),
                ('aliquot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aliquot')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.samples')),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labtest', models.CharField(blank=True, max_length=150)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.samples')),
            ],
        ),
        migrations.CreateModel(
            name='Comorbidities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity', models.CharField(blank=True, max_length=150)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.samples')),
            ],
        ),
        migrations.AddField(
            model_name='aliquot',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.samples'),
        ),
    ]
