# Generated by Django 4.0.1 on 2024-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rs_step4',
            name='multiple_samples',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='rs_step5',
            name='different_sources',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='rs_step5',
            name='multiple_timepoints_each',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
