# Generated by Django 5.1.1 on 2024-10-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comorbidities',
            name='comorbidity',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lab_test',
            name='labtest',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='samples',
            name='clinical_diagnosis',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samples',
            name='type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='samples',
            name='unit',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='storage',
            name='container',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
