# Generated by Django 4.0.1 on 2024-10-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_aliquot_unit_alter_comorbidities_comorbidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='aliquot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.aliquot'),
        ),
    ]
