# Generated by Django 5.1.3 on 2024-11-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_approve_reject_request_request_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ack_receipt',
            name='ack_sample_id',
        ),
    ]
