# Generated by Django 5.1.1 on 2024-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_approve_reject_request_create_ack_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
