# Generated by Django 5.1.1 on 2024-10-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_storage_aliquot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('ack_unit', models.CharField(max_length=100, null=True)),
                ('ack_position', models.CharField(max_length=300, null=True)),
                ('ack_sample_id', models.IntegerField(blank=True, null=True)),
                ('sample_type', models.CharField(max_length=300, null=True)),
                ('ack_quantity_volume', models.IntegerField(blank=True, null=True)),
                ('officer_name', models.CharField(max_length=300, null=True)),
                ('officer_position', models.CharField(max_length=300, null=True)),
                ('officer_signature', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Approve_Reject_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_file', models.FileField(blank=True, null=True, upload_to='')),
                ('reject_reason', models.CharField(max_length=300, null=True)),
                ('no_available_samples', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erb_approval', models.FileField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(max_length=300, null=True)),
                ('sex', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('clinical_diagnosis', models.CharField(max_length=300, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_start_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acknowledgement_Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_box_num', models.IntegerField(blank=True, null=True)),
                ('ack_container_num', models.IntegerField(blank=True, null=True)),
                ('acknowledgement_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.acknowledgement_receipt')),
            ],
        ),
        migrations.AddField(
            model_name='acknowledgement_receipt',
            name='approve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.approve_reject_request'),
        ),
        migrations.AddField(
            model_name='approve_reject_request',
            name='request_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample'),
        ),
        migrations.CreateModel(
            name='Research_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('principal_investigator', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('anticipated_initiation_date', models.DateField(null=True)),
                ('anticipated_completion_date', models.DateField(null=True)),
                ('erb_number', models.CharField(max_length=300, null=True)),
                ('funding_source', models.CharField(max_length=300, null=True)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='RS_Comorbidities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity', models.CharField(blank=True, max_length=300)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='RS_Lab_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labtest', models.CharField(blank=True, max_length=300)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='RS_Step4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_samples', models.CharField(null=True)),
                ('time_points', models.IntegerField(blank=True, null=True)),
                ('interval', models.CharField(blank=True, max_length=300)),
                ('interval_unit', models.CharField(blank=True, max_length=100)),
                ('start_date_ddmmyyyy', models.DateField(null=True)),
                ('start_date_mmyyyy', models.CharField(blank=True, max_length=7, null=True)),
                ('start_date_yyyy', models.CharField(blank=True, max_length=4, null=True)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
        migrations.CreateModel(
            name='RS_Step5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('different_sources', models.CharField(null=True)),
                ('num_participants', models.IntegerField(blank=True, null=True)),
                ('multiple_timepoints_each', models.CharField(null=True)),
                ('time_points', models.IntegerField(blank=True, null=True)),
                ('interval', models.CharField(blank=True, max_length=300)),
                ('interval_unit', models.CharField(blank=True, max_length=100)),
                ('start_date_ddmmyyyy', models.DateField(null=True)),
                ('start_date_mmyyyy', models.CharField(blank=True, max_length=7, null=True)),
                ('start_date_yyyy', models.CharField(blank=True, max_length=4, null=True)),
                ('collection_date_ddmmyyyy', models.DateField(null=True)),
                ('collection_date_mmyyyy', models.CharField(blank=True, max_length=7, null=True)),
                ('collection_date_yyyy', models.CharField(blank=True, max_length=4, null=True)),
                ('request_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.request_sample')),
            ],
        ),
    ]
