# Generated by Django 5.1.3 on 2024-11-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_create_ack_receipt_ack_sample_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rs_step4',
            old_name='time_points',
            new_name='time_points1',
        ),
        migrations.RenameField(
            model_name='rs_step5',
            old_name='time_points',
            new_name='time_points2',
        ),
    ]
