# Generated by Django 5.1.3 on 2024-11-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_create_ack_receipt_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ack_receipt',
            name='pdf_file',
        ),
    ]
