# Generated by Django 4.2.7 on 2024-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_storage_aliquot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='freezer_num',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
