# Generated by Django 5.1.1 on 2024-11-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_research_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
