# Generated by Django 5.1.3 on 2024-11-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_create_ack_receipt_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ack_receipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='ack_receipts/'),
        ),
    ]
