# Generated by Django 4.2.7 on 2024-12-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_create_ack_receipt_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_sample',
            name='age_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_sample',
            name='age_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
