# Generated by Django 4.2.7 on 2024-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_request_sample_age_from_request_sample_age_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_project',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
